services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  UserRankingBundle\Command\:
    resource: '../../Command/'
  UserRankingBundle\Controller\:
    resource: '../../Controller/'
  UserRankingBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  UserRankingBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  UserRankingBundle\Procedure\:
    resource: '../../Procedure/'
  UserRankingBundle\Repository\:
    resource: '../../Repository/'
  UserRankingBundle\Service\:
    resource: '../../Service/'
